### ISSUE TITLE
:kekw:

### ISSUE THREAD

**Issue by chadhyatt** [Roblox-Devs/roblox-channel-bruteforcer#1]
wordlist moment

![image](https://user-images.githubusercontent.com/56618074/234442866-e4982931-7c82-4ea2-b870-7b637557ffc7.png)

**Comment by stan2474** [comment]
your bruteforcer is more slow than the loading times on gta online because of the lack of a wordlist

**Comment by chadhyatt** [comment]
> your bruteforcer is more slow than the loading times on gta online because of the lack of a wordlist

500k reqs in ~4 min :muscle:

![image](https://user-images.githubusercontent.com/56618074/234443158-b6efd5b1-5123-4a29-bedf-e722d7861e1e.png)

![image](https://user-images.githubusercontent.com/56618074/234443486-5624526f-100a-48cb-9180-86b4f5ce05e2.png)

**Comment by stan2474** [comment]
> > your bruteforcer is more slow than the loading times on gta online because of the lack of a wordlist
> 
> 500k reqs in ~4 min 💪
> 
> ![image](https://user-images.githubusercontent.com/56618074/234443158-b6efd5b1-5123-4a29-bedf-e722d7861e1e.png)
> 
> ![image](https://user-images.githubusercontent.com/56618074/234443486-5624526f-100a-48cb-9180-86b4f5ce05e2.png)

we have just been notified by the roblox employees for you to STOP DOING THIS AS IT IS LAGGING THEM.....

**Comment by chadhyatt** [comment]
> we have just been notified by the roblox employees for you to STOP DOING THIS AS IT IS LAGGING THEM.....

:middle_finger:

**Comment by chadhyatt** [comment]
not actually up to pollos standards, reopen..
beat the unreleased s3forcer rewrite..

**Comment by stan2474** [comment]
> not actually up to pollos standards, reopen.. beat the unreleased s3forcer rewrite..

issue will reopen when s3forcer rewrite released

**Comment by chadhyatt** [comment]
never.
